### ISSUE TITLE
Recommended package versions?

### ISSUE THREAD

**Issue by d-shehu** [m-bain/whisperX#1333]
Can you someone suggest the recommended version for getting whisper x running with Python3.11 or 3.12 using Cuda 12.8 or Cuda 13 environment and pytorch? I've tried a few different combinations but something always breaks.

I had this working in September with Pytorch 2.7.1 I believe and possibly 3.4.2. But I neglected to checkpoint all the versions.  The most recent errors after downgrading to 2.7.1 and 3.4.2 are around omegaconf which was an easy fix and pyannote issues like this one.

Thanks in advance. 

```
line 196, in __init__
    super().__init__(segmentation=segmentation, fscore=fscore, use_auth_token=use_auth_token, **inference_kwargs)
  File "./lib/python3.11/site-packages/pyannote/audio/pipelines/voice_activity_detection.py", line 114, in __init__
    self._segmentation = Inference(model, **inference_kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Inference.__init__() got an unexpected keyword argument 'use_auth_token'
```

My requirements so far

```
-i https://download.pytorch.org/whl/cu128
torch==2.7.1
torchaudio==2.7.1
```

```
aiofiles
fastapi
httpx
jinja2
numpy
python-dotenv
python-ffmpeg
python-multipart
omegaconf
uvicorn
whisperx==3.4.2 # Fxing to avoid conflict with Pytorch/cuda

```

**Comment by d-shehu** [comment]
If anyone is curious I was able to get it to run again but i had to backtrack pip packages circa mid September 2025.

I would appreciate if someone has a set of versions that work with Pytorch 2.9.1 which is the minimal version I need for other apps. Latest would be best! Thanks. 

-----

Works with Cuda 12.8 / 13.0 environment ... with some alarming warnings. 

```
# Versions required for Whisperx 3.4.x
torch==2.5.1      -i https://download.pytorch.org/whl/cu124
torchaudio==2.5.1 -i https://download.pytorch.org/whl/cu124
```

```
omegaconf==2.3
pyannote-audio==3.4.0
huggingface-hub==0.35.0
transformers==4.56.2
whisperx==3.4.2 
```

**Comment by JIAWENee** [comment]
I encountered a similar issue before. Later, I compared the dependencies installed by running `uv sync --all-extras --dev` in the WhisperX project with those installed by running `pip install whisperx` in my own project, and found that the` pytorch-lightning` versions were different.

You might want to try:
```
pip install whisperx==3.7.6
pip install pytorch-lightning==2.5.5
```
This will install `torch 2.8.0`, which works with `CUDA 12.8` and `Python 3.11`.

Below are the dependencies I’m currently using:
```
-i https://download.pytorch.org/whl/cu128
torch==2.8.0
torchaudio==2.8.0
```
```
litserve==0.2.17
numpy==2.2.6
omegaconf==2.3.0
pandas==2.2.3
pyannote-audio==3.4.0
pytorch-lightning==2.5.5
soundfile==0.13.1
transformers==4.57.6
whisperx==3.7.6
```

**Comment by d-shehu** [comment]
Thanks, I documented this on my end. Closing as I'm gtg for now.

**Comment by julianpoemp** [comment]
a requirements.txt file for this package would be very helpful.

**Comment by Barabazs** [comment]
> a requirements.txt file for this package would be very helpful.

we use uv and thus work with a pyproject.toml instead of the requirements.txt

**Comment by d-shehu** [comment]
Perhaps you would consider adding a Docker recipe file which explicitly includes the non-python dependencies including pytorch & cuda?

I've done this on my end but it would be nice to have all deps documented in a reproducible recipe for anyone to quickly bootstrap their projects. 

Thanks for all the hard work on this project! It really is far superior to Google's Pixel transcription and Otter for my meeting notes.

**Comment by Barabazs** [comment]
There are too many variables like OS, CPU vs GPU, architecture, python versions, pre-installed binaries etc to maintain that. There are third party/community maintained docker projects if you want to try that, but we can't give support for that. For example https://github.com/jim60105/docker-whisperX by @jim60105
