### ISSUE TITLE
Solved: TypeError: TranscriptionOptions.__new__() got an unexpected keyword argument 'max_new_tokens'

### ISSUE THREAD

**Issue by longdaothanh** [m-bain/whisperX#711]
TypeError: TranscriptionOptions.__new__() got an unexpected keyword argument 'max_new_tokens'

Anyone has an idea how to fix this or has similar issues?

Problem Solved:
Change faster-whisper~=0.10.0 in requirements.txt to the newest version 1.0.0 then install -> working

**Comment by longdaothanh** [comment]
![Screenshot 2024-02-22 154235](https://github.com/m-bain/whisperX/assets/115090741/78f90a10-34e7-48e0-ad12-8680167eb593)

**Comment by longdaothanh** [comment]
![Screenshot 2024-02-22 190759](https://github.com/m-bain/whisperX/assets/115090741/9da3c2dc-62a2-4499-8647-aa3b51ba476c)

**Comment by SobolevskyDmitry** [comment]
Seems new faster-whisper broke it
https://github.com/SYSTRAN/faster-whisper/releases

For me `faster-whisper-0.10.0` worked fine, but today I got the same error as you and checked my deps and found a new version: `faster-whisper-0.10.1`

**Comment by SobolevskyDmitry** [comment]
I'm wondering would WhisperX work with https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.0.0 ?

**Comment by longdaothanh** [comment]
Hi, I just solved the problem 

> I'm wondering would WhisperX work with https://github.com/SYSTRAN/faster-whisper/releases/tag/v1.0.0 ?

Yes, I just tried and it worked perfect now.

**Comment by msfuko** [comment]
Hi, how do you override the faster-whisper from `git+https://github.com/m-bain/whisperx.git@d6562c26da467ca49866a4173c0e723f3837f367`? or do you fork it?

**Comment by davidmartinrius** [comment]
> Hi, how do you override the faster-whisper from `git+https://github.com/m-bain/whisperx.git@d6562c26da467ca49866a4173c0e723f3837f367`? or do you fork it?

after installing whisperx you can do this:

pip install --upgrade faster-whisper==1.0.0

**Comment by sushk0841** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-30a4dd61aaad>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model = whisperx.load_model("large-v2", device, compute_type=compute_type)

[/usr/local/lib/python3.10/dist-packages/whisperx/asr.py](https://localhost:8080/#) in load_model(whisper_arch, device, device_index, compute_type, asr_options, language, vad_model_fp, vad_options, model, task, download_root, threads)
    330     del default_asr_options["suppress_numerals"]
    331 
--> 332     default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
    333 
    334     default_vad_options = {

TypeError: TranscriptionOptions.__new__() missing 3 required positional arguments: 'max_new_tokens', 'clip_timestamps', and 'hallucination_silence_threshold'     i am still gettting this error after upgrading faster-whisper to 1.0.0
is there any solution?

**Comment by longdaothanh** [comment]
> TypeError Traceback (most recent call last) in <cell line: 1>() ----> 1 model = whisperx.load_model("large-v2", device, compute_type=compute_type)
> 
> [/usr/local/lib/python3.10/dist-packages/whisperx/asr.py](https://localhost:8080/#) in load_model(whisper_arch, device, device_index, compute_type, asr_options, language, vad_model_fp, vad_options, model, task, download_root, threads) 330 del default_asr_options["suppress_numerals"] 331 --> 332 default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options) 333 334 default_vad_options = {
> 
> TypeError: TranscriptionOptions.**new**() missing 3 required positional arguments: 'max_new_tokens', 'clip_timestamps', and 'hallucination_silence_threshold' i am still gettting this error after upgrading faster-whisper to 1.0.0 is there any solution?

I just tried to install it on colab and it ran so I don't know why you still had that problem

**Comment by davidmartinrius** [comment]
> TypeError Traceback (most recent call last) in <cell line: 1>() ----> 1 model = whisperx.load_model("large-v2", device, compute_type=compute_type)
> 
> [/usr/local/lib/python3.10/dist-packages/whisperx/asr.py](https://localhost:8080/#) in load_model(whisper_arch, device, device_index, compute_type, asr_options, language, vad_model_fp, vad_options, model, task, download_root, threads) 330 del default_asr_options["suppress_numerals"] 331 --> 332 default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options) 333 334 default_vad_options = {
> 
> TypeError: TranscriptionOptions.**new**() missing 3 required positional arguments: 'max_new_tokens', 'clip_timestamps', and 'hallucination_silence_threshold' i am still gettting this error after upgrading faster-whisper to 1.0.0 is there any solution?

Hi @sushk0841 ,

This way is working for my now:

pip install whisperx==3.1.1 
pip install --upgrade faster-whisper==0.10.1

I still haven't tried what @longdaothanh said

**Comment by davidmartinrius** [comment]
Update:
In addition to the above you will also have tu downgrade speechbrain:

pip install -U speechbrain==0.5.16 

Because of this https://github.com/m-bain/whisperX/issues/723

**Comment by souvikqb** [comment]
Hi @davidmartinrius 
I'm Getting this error even after the following requirements - 

TypeError: __new__() missing 3 required positional arguments: 'max_new_tokens', 'clip_timestamps', and 'hallucination_silence_threshold'

I'm using Docker to run the code and on CUDA 12.2

git+https://github.com/m-bain/whisperx.git
faster-whisper == 1.0.1
speechbrain == 0.5.16

**Comment by grzegorz700** [comment]
For me, the latest working version of WhisperX, with the capability of using Cuda 11.8 is:
`pip install git+https://github.com/m-bain/whisperx.git@8227807fa9e076901ea4b4fbbf79c9777a6f5e03 --no-deps`
And install whisperX requirements with replacement to 
`faster-whisper @ git+https://github.com/SYSTRAN/faster-whisper.git@v0.10.0`
The change is connected with ?replacement tag from 0.10.0  to **v**0.10.0 .

**Comment by deep-pipeline** [comment]
@longdaothanh are you satisfied this issue has now been solved? if so, could you close it please. Thank you.
