### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Macmartin85** [m-bain/whisperX#469]
File "C:\Users\mac\PycharmProjects\whisperX-main\main.py", line 11, in <module>
    model = whisperx.load_model("large-v2", device, compute_type=compute_type,language="en")
  File "C:\Users\mac\PycharmProjects\whisperX-main\whisperx\asr.py", line 92, in load_model
    default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
TypeError: TranscriptionOptions.__new__() got an unexpected keyword argument 'repetition_penalty'

**Comment by GuangDai** [comment]
same

**Comment by sorgfresser** [comment]
Most likely introduced by #458. @remic33 can you take a look? I'd say we should require a newer faster whisper version in `requirements.txt`, no?

**Comment by remic33** [comment]
It seems that my pr is no longer relevant, but I can not see the changes in fast whisper repo. Did they roll back on it? Or am i missing something?

**Comment by Macmartin85** [comment]
fix just add if "language" in result and result

line 287 if "language" in result and result

**Comment by sorgfresser** [comment]
@remic33 just added a pr to pin it, should be resolved with this.

**Comment by fernandesdiego** [comment]
> > > File "C:\Users\mac\PycharmProjects\whisperX-main\main.py", line 11, in
> > > model = whisperx.load_model("large-v2", device, compute_type=compute_type,language="en")
> > > File "C:\Users\mac\PycharmProjects\whisperX-main\whisperx\asr.py", line 92, in load_model
> > > default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
> > > TypeError: TranscriptionOptions.**new**() got an unexpected keyword argument 'repetition_penalty'
> > 
> > 
> > What is your version of faster whisper? Those options has been added to the main code last week.
> 
> problem solved I don't understand why fast whisper is not updated now I have this problem thanks for help
> 
> Traceback (most recent call last): File "C:\Users\mac\PycharmProjects\whisperX-main\main.py", line 52, in writesrt.write_result(result=result, file=srt,options={"max_line_width":None,"max_line_count":None,"highlight_words":False}) File "C:\Users\mac\PycharmProjects\whisperX-main\whisperx\utils.py", line 353, in write_result for i, (start, end, text) in enumerate( File "C:\Users\mac\PycharmProjects\whisperX-main\whisperx\utils.py", line 287, in iterate_result if result["language"] in LANGUAGES_WITHOUT_SPACES: KeyError: 'language'

Should the commit solve this one too? I still get KeyError when using the utils to write srt

**Comment by Macmartin85** [comment]
> > > > File "C:\Users\mac\PycharmProjects\whisperX-main\main.py", line 11, in
> > > > model = whisperx.load_model("large-v2", device, compute_type=compute_type,language="en")
> > > > File "C:\Users\mac\PycharmProjects\whisperX-main\whisperx\asr.py", line 92, in load_model
> > > > default_asr_options = faster_whisper.transcribe.TranscriptionOptions(**default_asr_options)
> > > > TypeError: TranscriptionOptions.**new**() got an unexpected keyword argument 'repetition_penalty'
> > > 
> > > 
> > > What is your version of faster whisper? Those options has been added to the main code last week.
> > 
> > 
> > problem solved I don't understand why fast whisper is not updated now I have this problem thanks for help
> > Traceback (most recent call last): File "C:\Users\mac\PycharmProjects\whisperX-main\main.py", line 52, in writesrt.write_result(result=result, file=srt,options={"max_line_width":None,"max_line_count":None,"highlight_words":False}) File "C:\Users\mac\PycharmProjects\whisperX-main\whisperx\utils.py", line 353, in write_result for i, (start, end, text) in enumerate( File "C:\Users\mac\PycharmProjects\whisperX-main\whisperx\utils.py", line 287, in iterate_result if result["language"] in LANGUAGES_WITHOUT_SPACES: KeyError: 'language'
> 
> Should the commit solve this one too? I still get KeyError when using the utils to write srt

nop

**Comment by fernandesdiego** [comment]
ok, thanks anyway, the change on line 287 fixed it for me
